<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <RootNamespace>c_lan</RootNamespace>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Services\" />
    <Folder Include="Data\" />
    <Folder Include="Configuration\" />
    <Folder Include="Utilities\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="System.Data.Common" Version="4.3.0" />
  </ItemGroup>

</Project>